### ISSUE TITLE
Feature request: static avif libs 

### ISSUE THREAD

**Issue by Jan-E** [winlibs/libavif#1]
@cmb69 @morsssss 
This repo, combined with https://github.com/php/php-src/pull/7026 and https://github.com/php/php-src/commit/81f6d36c90b8626660a6571cdc128265fa00697f results in building a php_gd.dll that is dependent on avif.dll. From the snapshot.txt of php-8.1.0alpha2-nts-Win32-vs16-x64.zip
```
Module: php_gd.dll
===========================
	avif.dll
```
I would prefer to keep php_gd.dll fully static, without external dependencies. Then 2 things are needed:

1. Build a static avif_a.lib which can be linked while building php_gd.dll in PHP 8.1+
2. Allow linking avif_a.lib in the gd extension of php-src

**Comment by Jan-E** [comment]
Building static libs for libavif is done in my fork of this repo:
https://github.com/Jan-E/libavif

See the resulting artifacts:
https://github.com/Jan-E/libavif/actions/runs/972759402#artifacts

**Comment by Jan-E** [comment]
Allow linking avif_a.lib in the gd extension of php-src needs a PR for php-src. I already prepared one:
https://github.com/Jan-E/php-src/commit/f8816e7fc81b2f5375769b6fe9ea441d81a8751c

**Comment by Jan-E** [comment]
I have built PHP 8.1 alpha2 with these changes:
https://www.apachelounge.com/viewtopic.php?t=6617

I also did run the tests. Example for x64, NTS:
```
=====================================================================
Number of tests :  275               269
Tests skipped   :    6 (  2.2%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Tests passed    :  269 ( 97.8%) (100.0%)
---------------------------------------------------------------------
Time taken      :   56 seconds
=====================================================================
```
Skip reasons: `requires extern GD`, `UTF-8 font file names not yet supported on Windows`, `only for external libgd < 2.2.4`.

The avif decoding/encoding test [gd/tests/avif_decode_encode.phpt] takes a long time on my system (23-25 seconds), but there is no significant difference between the version with static libs and the version with an external avif.dll.

**Comment by cmb69** [comment]
I had build the dynamic avif.dll to avoid the hard-coded dependency on the codec. However, given that it is somewhat unlikely that we switch to another codec, building and using a static avif_a.lib may be fine as well. Do you want to provide a PR?

**Comment by Jan-E** [comment]
https://github.com/Jan-E/libavif needs a little bit of explaining.

1. While building the AV1 Codec library at https://aomedia.googlesource.com/aom for Windows a lot of libs are created. Some of them are in the artifacts of https://github.com/Jan-E/libavif/actions/runs/971607266
2. I could not find an easy way to build a 'fat' avif.lib which included all of the aom-code, so linking avif.lib and aom*.lib seemed the only option for php_gd.dll
3. As far as I know, aom.lib is the only one of all the aom*.lib's that needs to be linked in the php_gd.dll extension
4. On Windows we prefer avif_a.lib for a static lib, this in contrast to avif.lib which dynamically loads avif.dll
5. I made a tiny change to the CMakeLists.txt of libavif to make it produce a avif_a.lib: `set(CMAKE_STATIC_LIBRARY_SUFFIX "_a.lib")`. That would be a change that is specific for the winlibs repo. Effect was that I also needed to rename aom.lib to aom_a.lib during the bjuild process.

**Comment by Jan-E** [comment]
> I had build the dynamic avif.dll to avoid the hard-coded dependency on the codec. However, given that it is somewhat unlikely that we switch to another codec, building and using a static avif_a.lib may be fine as well.

I was thinking the same. And besides that `avif.dll` would be the only external dependency of php_gd.dll. And the only external dependency of extensions that use a `ADD_EXTENSION_DEP("other_ext", "gd", true)` (like my php_ffmpeg.dll extension).

With https://github.com/php/php-src/commit/f8816e7fc81b2f5375769b6fe9ea441d81a8751c in https://github.com/php/php-src/pull/7200 it is easy to switch back to a dynamic avif.dll. If the dependent zips do not contain avif_a.lib and aom_a.lib, building will revert to avif.lib and avif.dll.

**Comment by Jan-E** [comment]
BTW: I have my doubts about the use of `HAVE_LIBAVIF`, because it only is a limited libavif with only 1 codec. Would not it be better to remove HAVE_LIBAVIF from config.m4 and config.w32 and change `HAVE_LIBAVIF` into `HAVE_GD_AVIF` in the extension code it self:
https://github.com/php/php-src/blob/81f6d36c90b8626660a6571cdc128265fa00697f/ext/gd/libgd/gd_avif.c#L16

@morsssss Would you comment on that?

**Comment by Jan-E** [comment]
> Do you want to provide a PR?

Sure. The PR for php-src is here: https://github.com/php/php-src/pull/7200
I will create a PR for this repo shortly.

**Comment by Jan-E** [comment]
> I will create a PR for this repo shortly.

@cmb69 Do you want a separate branch, so you can still build avif.lib and avif.dll? Is so, can you create that branch?

**Comment by cmb69** [comment]
I think it's fine to switch to static.

**Comment by Jan-E** [comment]
PR for this repo: https://github.com/winlibs/libavif/pull/2

**Comment by Jan-E** [comment]
> The PR for php-src is here: https://github.com/php/php-src/pull/7200

@krakjoe added the ‘Wating for review’ label to that PR. @cmb69 could you review it?

**Comment by cmb69** [comment]
> The avif decoding/encoding test [gd/tests/avif_decode_encode.phpt] takes a long time on my system (23-25 seconds), […]

There is a [ticket about this](https://bugs.php.net/bug.php?id=81127); I hope it will be resolved soon

Anyhow, PR #2 has been applied, so this can be closed.

**Comment by pierrejoye** [comment]
Please also open a ticket here, that's where it can be solved I think.

@Jan-E about the execution time, did you run a profile by any chance? Like where it spent most time?

**Comment by Jan-E** [comment]
> Please also open a ticket here, that's where it can be solved I think.

Was not @morsssss experiencing this problem on *nix? https://bugs.php.net/bug.php?id=81127 mentions "OS: all".

> @Jan-E about the execution time, did you run a profile by any chance? Like where it spent most time?

No, I did not, presuming it was an OS-independent issue.

**Comment by morsssss** [comment]
I wanted to get https://github.com/php/php-src/pull/7091 out the door first, but that slow test is an easy fix. Today I made https://github.com/php/php-src/pull/7211 to speed it up.

**Comment by Jan-E** [comment]
OK, this reduced the time taken on Win10, x64, nts from 23 seconds to 3 seconds.
